Output ../assets/demo/sandbox-create.gif

Require orrery-bin

Set Shell "zsh"
Set FontSize 32
Set Width 1200
Set Height 1200

Hide
Type "source ~/.orrery/activate.sh"
Enter
Sleep 500ms
Type "clear"
Enter
Show

Type "orrery sandbox create demo"
Sleep 0.5s
Enter
Sleep 1s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Enter
Sleep 2s

Type "Y"
Enter
Sleep 3s

Type "claude"
Sleep 0.5s
Enter
Sleep 5s

Enter
Sleep 2s